<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIFWbMLr\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIFWbMLr/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerIFWbMLr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerIFWbMLr\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerIFWbMLr\srcApp_KernelProdContainer([
    'container.build_hash' => 'IFWbMLr',
    'container.build_id' => '245fe7f6',
    'container.build_time' => 1613990710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIFWbMLr');
